name: autopep8
on:
  push:
    branches:
      - main
jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run autopep8
      run: |
        output=$(python -m autopep8 --diff -r --aggressive --aggressive hw2_debugging.py rand.py tests)
        
        # If differences are found, fail the action
        if [ -n "$output" ]; then
          echo "Formatting issues detected!"
          echo "$output"
          exit 1  # Fail the action
        else
          echo "No formatting issues."
        fi